/* eslint-disable */
import { StoryblokStory, Richtext } from 'storyblok-generate-ts'

/* eslint-disable */
/**
 * This type/interface was automatically generated by the storyblok:generate command.
 * DO NOT MODIFY IT BY HAND. Instead, download the schema from storyblok (storyblok:download),
 * and run storyblok:generate to regenerate this file.
 */

export interface SbAccordion {
  has_link_list?: boolean
  entries?: SbAccordionEntry[]
  margin_top?: '' | 'xs' | 'sm' | 'md' | 'lg' | 'xl'
  _uid: string
  component: 'Accordion'
}

/* eslint-disable */
/**
 * This type/interface was automatically generated by the storyblok:generate command.
 * DO NOT MODIFY IT BY HAND. Instead, download the schema from storyblok (storyblok:download),
 * and run storyblok:generate to regenerate this file.
 */

export interface SbAccordionEntry {
  title?: string
  link_title: string
  body?: Richtext
  _uid: string
  component: 'AccordionEntry'
}

/* eslint-disable */
/**
 * This type/interface was automatically generated by the storyblok:generate command.
 * DO NOT MODIFY IT BY HAND. Instead, download the schema from storyblok (storyblok:download),
 * and run storyblok:generate to regenerate this file.
 */

export type Sbmultilink =
  | {
      id?: string
      cached_url?: string
      anchor?: string
      linktype?: 'story'
      story?: {
        name: string
        created_at?: string
        published_at?: string
        id: number
        uuid: string
        content?: {}
        slug: string
        full_slug: string
        sort_by_date?: null | string
        position?: number
        tag_list?: string[]
        is_startpage?: boolean
        parent_id?: null | number
        meta_data?: null | {}
        group_id?: string
        first_published_at?: string
        release_id?: null | number
        lang?: string
        path?: null | string
        alternates?: any[]
        default_full_slug?: null | string
        translated_slugs?: null | any[]
      }
    }
  | {
      url?: string
      cached_url?: string
      anchor?: string
      linktype?: 'asset' | 'url'
    }
  | {
      email?: string
      linktype?: 'email'
    }

/* eslint-disable */
/**
 * This type/interface was automatically generated by the storyblok:generate command.
 * DO NOT MODIFY IT BY HAND. Instead, download the schema from storyblok (storyblok:download),
 * and run storyblok:generate to regenerate this file.
 */

export interface SbBanner {
  is_active?: boolean
  type?: '' | 'info' | 'sale' | 'highlight'
  body?: Richtext
  countdown_until?: string
  links?: SbBannerLink[]
  item_id: string
  item_name: string
  promotion_id: string
  promotion_name: string
  creative_name: string
  creative_slot: string
  location_id: string
  index: string
  cta_url?: Exclude<
    Sbmultilink,
    { linktype?: 'email' } | { linktype?: 'asset' }
  >
  _uid: string
  component: 'Banner'
}

/* eslint-disable */
/**
 * This type/interface was automatically generated by the storyblok:generate command.
 * DO NOT MODIFY IT BY HAND. Instead, download the schema from storyblok (storyblok:download),
 * and run storyblok:generate to regenerate this file.
 */

export interface SbBannerLink {
  label?: string
  cta_url?: Exclude<
    Sbmultilink,
    { linktype?: 'email' } | { linktype?: 'asset' }
  >
  item_id?: string
  item_name?: string
  promotion_id?: string
  promotion_name?: string
  creative_name?: string
  creative_slot?: string
  location_id?: string
  index?: string
  _uid: string
  component: 'BannerLink'
}

/* eslint-disable */
/**
 * This type/interface was automatically generated by the storyblok:generate command.
 * DO NOT MODIFY IT BY HAND. Instead, download the schema from storyblok (storyblok:download),
 * and run storyblok:generate to regenerate this file.
 */

export interface SbClickableImage {
  item_id?: string
  image: SbCmsImage[]
  cta_url: Exclude<Sbmultilink, { linktype?: 'email' } | { linktype?: 'asset' }>
  item_name?: string
  promotion_id?: string
  promotion_name?: string
  creative_name?: string
  creative_slot?: string
  location_id?: string
  index?: string
  margin_top?: '' | 'xs' | 'sm' | 'md' | 'lg' | 'xl' | '2xl'
  _uid: string
  component: 'ClickableImage'
}

/* eslint-disable */
/**
 * This type/interface was automatically generated by the storyblok:generate command.
 * DO NOT MODIFY IT BY HAND. Instead, download the schema from storyblok (storyblok:download),
 * and run storyblok:generate to regenerate this file.
 */

export interface Sbasset {
  alt?: string
  copyright?: string
  id: number
  filename: string
  name: string
  title?: string
  focus?: string
}

/* eslint-disable */
/**
 * This type/interface was automatically generated by the storyblok:generate command.
 * DO NOT MODIFY IT BY HAND. Instead, download the schema from storyblok (storyblok:download),
 * and run storyblok:generate to regenerate this file.
 */

export interface SbCmsImage {
  desktop_image?: Sbasset
  mobile_image?: Sbasset
  item_id?: string
  item_name?: string
  promotion_id?: string
  promotion_name?: string
  creative_name?: string
  creative_slot?: string
  location_id?: string
  index?: string
  _uid: string
  component: 'CmsImage'
}

/* eslint-disable */
/**
 * This type/interface was automatically generated by the storyblok:generate command.
 * DO NOT MODIFY IT BY HAND. Instead, download the schema from storyblok (storyblok:download),
 * and run storyblok:generate to regenerate this file.
 */

export interface SbCmsText {
  body?: Richtext
  _uid: string
  component: 'CmsText'
}

/* eslint-disable */
/**
 * This type/interface was automatically generated by the storyblok:generate command.
 * DO NOT MODIFY IT BY HAND. Instead, download the schema from storyblok (storyblok:download),
 * and run storyblok:generate to regenerate this file.
 */

export interface SbContentPage {
  teaser_image?: Sbasset
  teaser_image_mobile?: Sbasset
  headline?: string
  subline?: string
  content?: (
    | SbCmsImage
    | SbCmsText
    | SbGrid
    | SbImageSlider
    | SbProductSlider
    | SbSlideShow
    | SbSocialMediaLink
    | SbVideo
    | SbAccordion
    | SbCustomerServiceInfo
    | SbDoubleColumn
    | SbParagraph
  )[]
  SEO?: {
    _uid?: string
    title?: string
    plugin?: string
    og_image?: string
    og_title?: string
    description?: string
    twitter_image?: string
    twitter_title?: string
    og_description?: string
    twitter_description?: string
  }
  _uid: string
  component: 'ContentPage'
}

/* eslint-disable */
/**
 * This type/interface was automatically generated by the storyblok:generate command.
 * DO NOT MODIFY IT BY HAND. Instead, download the schema from storyblok (storyblok:download),
 * and run storyblok:generate to regenerate this file.
 */

export interface SbCustomerServiceInfo {
  _uid: string
  component: 'CustomerServiceInfo'
}

/* eslint-disable */
/**
 * This type/interface was automatically generated by the storyblok:generate command.
 * DO NOT MODIFY IT BY HAND. Instead, download the schema from storyblok (storyblok:download),
 * and run storyblok:generate to regenerate this file.
 */

export interface SbDetailImage {
  image: Sbasset
  product_ids?: string
  _uid: string
  component: 'DetailImage'
}

/* eslint-disable */
/**
 * This type/interface was automatically generated by the storyblok:generate command.
 * DO NOT MODIFY IT BY HAND. Instead, download the schema from storyblok (storyblok:download),
 * and run storyblok:generate to regenerate this file.
 */

export interface SbDoubleColumn {
  column_left?: (
    | SbAccordion
    | SbAccordionEntry
    | SbBanner
    | SbBannerLink
    | SbClickableImage
    | SbCmsImage
    | SbCmsText
    | SbContentPage
    | SbCustomerServiceInfo
    | SbDetailImage
    | SbDoubleColumn
    | SbFooter
    | SbGrid
    | SbGridTile
    | SbImageSlider
    | SbImageSliderSlide
    | SbImageText
    | SbLink
    | SbLinkGroup
    | SbListingDisruptor
    | SbListingPage
    | SbNewsletter
    | SbPage
    | SbParagraph
    | SbProduct
    | SbProductSlider
    | SbShopableImage
    | SbSlide
    | SbSlideShow
    | SbSocialMediaLink
    | SbStore
    | SbStorePage
    | SbStory
    | SbTitle
    | SbVideo
  )[]
  column_right?: (
    | SbAccordion
    | SbAccordionEntry
    | SbBanner
    | SbBannerLink
    | SbClickableImage
    | SbCmsImage
    | SbCmsText
    | SbContentPage
    | SbCustomerServiceInfo
    | SbDetailImage
    | SbDoubleColumn
    | SbFooter
    | SbGrid
    | SbGridTile
    | SbImageSlider
    | SbImageSliderSlide
    | SbImageText
    | SbLink
    | SbLinkGroup
    | SbListingDisruptor
    | SbListingPage
    | SbNewsletter
    | SbPage
    | SbParagraph
    | SbProduct
    | SbProductSlider
    | SbShopableImage
    | SbSlide
    | SbSlideShow
    | SbSocialMediaLink
    | SbStore
    | SbStorePage
    | SbStory
    | SbTitle
    | SbVideo
  )[]
  margin_top?: '' | 'xs' | 'sm' | 'md' | 'lg' | 'xl' | '2xl' | '3xl' | '4xl'
  _uid: string
  component: 'DoubleColumn'
}

/* eslint-disable */
/**
 * This type/interface was automatically generated by the storyblok:generate command.
 * DO NOT MODIFY IT BY HAND. Instead, download the schema from storyblok (storyblok:download),
 * and run storyblok:generate to regenerate this file.
 */

export interface SbFooter {
  text?: Richtext
  align_right?: boolean
  link_groups?: SbLinkGroup[]
  text_bottom?: string
  social_media?: SbSocialMediaLink[]
  _uid: string
  component: 'Footer'
}

/* eslint-disable */
/**
 * This type/interface was automatically generated by the storyblok:generate command.
 * DO NOT MODIFY IT BY HAND. Instead, download the schema from storyblok (storyblok:download),
 * and run storyblok:generate to regenerate this file.
 */

export interface SbGrid {
  margin_top?: '' | 'xs' | 'sm' | 'md' | 'lg' | 'xl' | '2xl' | '3xl' | '4xl'
  is_containered?: boolean
  is_containered_desktop?: boolean
  is_spaced?: boolean
  columns?: (
    | SbShopableImage
    | SbProduct
    | SbClickableImage
    | SbParagraph
    | SbVideo
    | SbCmsImage
    | SbCmsText
    | SbGridTile
    | SbImageText
  )[]
  _uid: string
  component: 'Grid'
}

/* eslint-disable */
/**
 * This type/interface was automatically generated by the storyblok:generate command.
 * DO NOT MODIFY IT BY HAND. Instead, download the schema from storyblok (storyblok:download),
 * and run storyblok:generate to regenerate this file.
 */

export interface SbGridTile {
  content: (
    | SbShopableImage
    | SbProduct
    | SbClickableImage
    | SbVideo
    | SbCmsImage
  )[]
  headline?: string
  cta?: string
  cta_link?: Exclude<
    Sbmultilink,
    { linktype?: 'email' } | { linktype?: 'asset' }
  >
  _uid: string
  component: 'GridTile'
}

/* eslint-disable */
/**
 * This type/interface was automatically generated by the storyblok:generate command.
 * DO NOT MODIFY IT BY HAND. Instead, download the schema from storyblok (storyblok:download),
 * and run storyblok:generate to regenerate this file.
 */

export interface SbImageSlider {
  headline?: string
  cta_label?: string
  cta_url?: string
  slides?: SbImageSliderSlide[]
  margin_top?: '' | 'xs' | 'sm' | 'md' | 'lg' | 'xl' | '2xl'
  _uid: string
  component: 'ImageSlider'
}

/* eslint-disable */
/**
 * This type/interface was automatically generated by the storyblok:generate command.
 * DO NOT MODIFY IT BY HAND. Instead, download the schema from storyblok (storyblok:download),
 * and run storyblok:generate to regenerate this file.
 */

export interface SbImageSliderSlide {
  image: Sbasset
  topline?: string
  headline: string
  is_new?: boolean
  cta_label: string
  cta_url: Exclude<Sbmultilink, { linktype?: 'email' } | { linktype?: 'asset' }>
  item_id?: string
  item_name?: string
  promotion_id?: string
  promotion_name?: string
  creative_name?: string
  creative_slot?: string
  location_id?: string
  index?: string
  _uid: string
  component: 'ImageSliderSlide'
}

/* eslint-disable */
/**
 * This type/interface was automatically generated by the storyblok:generate command.
 * DO NOT MODIFY IT BY HAND. Instead, download the schema from storyblok (storyblok:download),
 * and run storyblok:generate to regenerate this file.
 */

export interface SbImageText {
  align?: 'start' | 'center' | 'end'
  image: SbCmsImage[]
  topline?: string
  headline?: string
  text?: string
  cta?: string
  cta_link?: Exclude<
    Sbmultilink,
    { linktype?: 'email' } | { linktype?: 'asset' }
  >
  justify?: 'start' | 'center' | 'end'
  _uid: string
  component: 'ImageText'
}

/* eslint-disable */
/**
 * This type/interface was automatically generated by the storyblok:generate command.
 * DO NOT MODIFY IT BY HAND. Instead, download the schema from storyblok (storyblok:download),
 * and run storyblok:generate to regenerate this file.
 */

export interface SbLink {
  label: string
  cta_url: Exclude<Sbmultilink, { linktype?: 'email' } | { linktype?: 'asset' }>
  open_in_new_tab?: boolean
  _uid: string
  component: 'Link'
}

/* eslint-disable */
/**
 * This type/interface was automatically generated by the storyblok:generate command.
 * DO NOT MODIFY IT BY HAND. Instead, download the schema from storyblok (storyblok:download),
 * and run storyblok:generate to regenerate this file.
 */

export interface SbLinkGroup {
  title?: string
  links?: SbLink[]
  _uid: string
  component: 'LinkGroup'
}

/* eslint-disable */
/**
 * This type/interface was automatically generated by the storyblok:generate command.
 * DO NOT MODIFY IT BY HAND. Instead, download the schema from storyblok (storyblok:download),
 * and run storyblok:generate to regenerate this file.
 */

export interface SbListingDisruptor {
  content?: (SbGrid | SbProduct | SbCmsImage)[]
  is_containered?: boolean
  width?: '' | '1' | '2' | 'full'
  insert_in_row?: string
  _uid: string
  component: 'ListingDisruptor'
}

/* eslint-disable */
/**
 * This type/interface was automatically generated by the storyblok:generate command.
 * DO NOT MODIFY IT BY HAND. Instead, download the schema from storyblok (storyblok:download),
 * and run storyblok:generate to regenerate this file.
 */

export interface SbListingPage {
  teaser_image?: Sbasset
  teaser_image_mobile?: Sbasset
  pre_listing_content?: (
    | SbAccordion
    | SbAccordionEntry
    | SbBanner
    | SbBannerLink
    | SbClickableImage
    | SbCmsImage
    | SbCmsText
    | SbContentPage
    | SbCustomerServiceInfo
    | SbDetailImage
    | SbDoubleColumn
    | SbFooter
    | SbGrid
    | SbGridTile
    | SbImageSlider
    | SbImageSliderSlide
    | SbImageText
    | SbLink
    | SbLinkGroup
    | SbListingDisruptor
    | SbListingPage
    | SbNewsletter
    | SbPage
    | SbParagraph
    | SbProduct
    | SbProductSlider
    | SbShopableImage
    | SbSlide
    | SbSlideShow
    | SbSocialMediaLink
    | SbStore
    | SbStorePage
    | SbStory
    | SbTitle
    | SbVideo
  )[]
  listing?: SbListingDisruptor[]
  SEO?: {
    _uid?: string
    title?: string
    plugin?: string
    og_image?: string
    og_title?: string
    description?: string
    twitter_image?: string
    twitter_title?: string
    og_description?: string
    twitter_description?: string
  }
  post_listing_content?: (
    | SbAccordion
    | SbAccordionEntry
    | SbBanner
    | SbBannerLink
    | SbClickableImage
    | SbCmsImage
    | SbCmsText
    | SbContentPage
    | SbCustomerServiceInfo
    | SbDetailImage
    | SbDoubleColumn
    | SbFooter
    | SbGrid
    | SbGridTile
    | SbImageSlider
    | SbImageSliderSlide
    | SbImageText
    | SbLink
    | SbLinkGroup
    | SbListingDisruptor
    | SbListingPage
    | SbNewsletter
    | SbPage
    | SbParagraph
    | SbProduct
    | SbProductSlider
    | SbShopableImage
    | SbSlide
    | SbSlideShow
    | SbSocialMediaLink
    | SbStore
    | SbStorePage
    | SbStory
    | SbTitle
    | SbVideo
  )[]
  _uid: string
  component: 'ListingPage'
}

/* eslint-disable */
/**
 * This type/interface was automatically generated by the storyblok:generate command.
 * DO NOT MODIFY IT BY HAND. Instead, download the schema from storyblok (storyblok:download),
 * and run storyblok:generate to regenerate this file.
 */

export interface SbNewsletter {
  upper_text?: string
  lower_text?: string
  _uid: string
  component: 'Newsletter'
}

/* eslint-disable */
/**
 * This type/interface was automatically generated by the storyblok:generate command.
 * DO NOT MODIFY IT BY HAND. Instead, download the schema from storyblok (storyblok:download),
 * and run storyblok:generate to regenerate this file.
 */

export interface SbPage {
  teaser_image?: Sbasset
  teaser_image_mobile?: Sbasset
  content?: (
    | SbCmsImage
    | SbCmsText
    | SbGrid
    | SbImageSlider
    | SbProductSlider
    | SbSlideShow
    | SbSocialMediaLink
    | SbVideo
    | SbAccordion
    | SbCustomerServiceInfo
    | SbDoubleColumn
    | SbParagraph
  )[]
  SEO?: {
    _uid?: string
    title?: string
    plugin?: string
    og_image?: string
    og_title?: string
    description?: string
    twitter_image?: string
    twitter_title?: string
    og_description?: string
    twitter_description?: string
  }
  _uid: string
  component: 'Page'
}

/* eslint-disable */
/**
 * This type/interface was automatically generated by the storyblok:generate command.
 * DO NOT MODIFY IT BY HAND. Instead, download the schema from storyblok (storyblok:download),
 * and run storyblok:generate to regenerate this file.
 */

export type Sbmultiasset = {
  alt?: string
  copyright?: string
  id: number
  filename: string
  name: string
  title?: string
}[]

/* eslint-disable */
/**
 * This type/interface was automatically generated by the storyblok:generate command.
 * DO NOT MODIFY IT BY HAND. Instead, download the schema from storyblok (storyblok:download),
 * and run storyblok:generate to regenerate this file.
 */

export interface SbParagraph {
  headline?: string
  cta?: Exclude<Sbmultilink, { linktype?: 'asset' }>
  body?: Richtext
  sub_title?: string
  images?: Sbmultiasset
  _uid: string
  component: 'Paragraph'
}

/* eslint-disable */
/**
 * This type/interface was automatically generated by the storyblok:generate command.
 * DO NOT MODIFY IT BY HAND. Instead, download the schema from storyblok (storyblok:download),
 * and run storyblok:generate to regenerate this file.
 */

export interface SbProduct {
  product_id?: string
  _uid: string
  component: 'Product'
}

/* eslint-disable */
/**
 * This type/interface was automatically generated by the storyblok:generate command.
 * DO NOT MODIFY IT BY HAND. Instead, download the schema from storyblok (storyblok:download),
 * and run storyblok:generate to regenerate this file.
 */

export interface SbProductSlider {
  headline?: string
  cta_label?: string
  cta_url?: string
  product_ids?: string
  margin_top?: '' | 'xs' | 'sm' | 'md' | 'lg' | 'xl' | '2xl'
  _uid: string
  component: 'ProductSlider'
}

/* eslint-disable */
/**
 * This type/interface was automatically generated by the storyblok:generate command.
 * DO NOT MODIFY IT BY HAND. Instead, download the schema from storyblok (storyblok:download),
 * and run storyblok:generate to regenerate this file.
 */

export interface SbShopableImage {
  image?: SbCmsImage[]
  detail_images?: SbDetailImage[]
  title?: string
  product_ids?: string
  margin_top?: '' | 'xs' | 'sm' | 'md' | 'lg' | 'xl' | '2xl'
  _uid: string
  component: 'ShopableImage'
}

/* eslint-disable */
/**
 * This type/interface was automatically generated by the storyblok:generate command.
 * DO NOT MODIFY IT BY HAND. Instead, download the schema from storyblok (storyblok:download),
 * and run storyblok:generate to regenerate this file.
 */

export interface SbSlide {
  image?: (SbCmsImage | SbVideo)[]
  topline?: string
  headline?: string
  cta_label?: string
  cta_url?: Exclude<
    Sbmultilink,
    { linktype?: 'email' } | { linktype?: 'asset' }
  >
  is_dark?: boolean
  align?: 'start' | 'center' | 'end'
  justify?: 'start' | 'center' | 'end'
  _uid: string
  component: 'Slide'
}

/* eslint-disable */
/**
 * This type/interface was automatically generated by the storyblok:generate command.
 * DO NOT MODIFY IT BY HAND. Instead, download the schema from storyblok (storyblok:download),
 * and run storyblok:generate to regenerate this file.
 */

export interface SbSlideShow {
  h1?: string
  slides?: SbSlide[]
  margin_top?: '' | 'xs' | 'sm' | 'md' | 'lg' | 'xl' | '2xl'
  _uid: string
  component: 'SlideShow'
}

/* eslint-disable */
/**
 * This type/interface was automatically generated by the storyblok:generate command.
 * DO NOT MODIFY IT BY HAND. Instead, download the schema from storyblok (storyblok:download),
 * and run storyblok:generate to regenerate this file.
 */

export interface SbSocialMediaLink {
  type: '' | 'facebook' | 'instagram' | 'snapchat' | 'twitter' | 'youtube'
  url?: Exclude<Sbmultilink, { linktype?: 'email' } | { linktype?: 'asset' }>
  isActive: boolean
  _uid: string
  component: 'SocialMediaLink'
}

/* eslint-disable */
/**
 * This type/interface was automatically generated by the storyblok:generate command.
 * DO NOT MODIFY IT BY HAND. Instead, download the schema from storyblok (storyblok:download),
 * and run storyblok:generate to regenerate this file.
 */

export interface SbStore {
  image?: Sbasset
  city?: string
  name: Richtext
  address: Richtext
  opening_hours?: Richtext
  contact?: Richtext
  phone?: string
  email?: string
  SEO?: {
    _uid?: string
    title?: string
    plugin?: string
    og_image?: string
    og_title?: string
    description?: string
    twitter_image?: string
    twitter_title?: string
    og_description?: string
    twitter_description?: string
  }
  _uid: string
  component: 'Store'
}

/* eslint-disable */
/**
 * This type/interface was automatically generated by the storyblok:generate command.
 * DO NOT MODIFY IT BY HAND. Instead, download the schema from storyblok (storyblok:download),
 * and run storyblok:generate to regenerate this file.
 */

export interface SbStorePage {
  teaser_image: SbCmsImage[]
  contact_email: string
  SEO?: {
    _uid?: string
    title?: string
    plugin?: string
    og_image?: string
    og_title?: string
    description?: string
    twitter_image?: string
    twitter_title?: string
    og_description?: string
    twitter_description?: string
  }
  _uid: string
  component: 'StorePage'
}

/* eslint-disable */
/**
 * This type/interface was automatically generated by the storyblok:generate command.
 * DO NOT MODIFY IT BY HAND. Instead, download the schema from storyblok (storyblok:download),
 * and run storyblok:generate to regenerate this file.
 */

export interface SbStory {
  color?: string
  image?: Sbasset
  label?: string
  cta_url?: string
  _uid: string
  component: 'Story'
}

/* eslint-disable */
/**
 * This type/interface was automatically generated by the storyblok:generate command.
 * DO NOT MODIFY IT BY HAND. Instead, download the schema from storyblok (storyblok:download),
 * and run storyblok:generate to regenerate this file.
 */

export interface SbTitle {
  text?: string
  image?: Sbasset
  _uid: string
  component: 'Title'
}

/* eslint-disable */
/**
 * This type/interface was automatically generated by the storyblok:generate command.
 * DO NOT MODIFY IT BY HAND. Instead, download the schema from storyblok (storyblok:download),
 * and run storyblok:generate to regenerate this file.
 */

export interface SbVideo {
  margin_top?: '' | 'xs' | 'sm' | 'md' | 'lg' | 'xl' | '2xl' | '3xl' | '4xl'
  control_color?: string
  autoplay?: boolean
  has_controls?: boolean
  is_containered?: boolean
  video: Sbasset
  preview_desktop_image?: Sbasset
  preview_mobile_image?: Sbasset
  item_id?: string
  item_name?: string
  promotion_id?: string
  promotion_name?: string
  creative_name?: string
  creative_slot?: string
  location_id?: string
  index?: string
  loop?: boolean
  _uid: string
  component: 'Video'
}
